### PR TITLE
Added new colorscheme breeze light

### PR DESCRIPTION
**Pull request by pratikmullick**
Created a new color scheme Breeze Light.

### CODE REVIEW

**Comment by mbadolato** [comment]
Thanks for submitting!

Can you please add the screenshot and link to it, along with your credits, in the README?

**Comment by pratikmullick** [comment]
Added screenshots as a png file in screenshots directory; and added credits and screenshot image link to README.md

**Comment by mbadolato** [comment]
@pratikmullick Did you mean to close this?

**Comment by pratikmullick** [comment]
Hi Mark,

I am not well-versed in using Github, especially forking and contributing to open source projects, so I apologize at the beginning. I guess I have to create a new pull request just to make my sync with your repository. I don't know what will happen to this pull request, whether it will be merged with the new one or not.

Regards,
Pratik

**Comment by mbadolato** [comment]
Hi @pratikmullick all good! I merged it. thanks!

**Comment by pratikmullick** [comment]
Hi Mark,

I think this pull request should be closed, since there are already way too many issues, and these commits are way behind your commits. I have re-forked your repository, and it is up to date.

I will upload the Breeze Light scheme in a new pull request.

**Pull request closed without merging**
