### PR TITLE
Re-add theme as Solarized Dark - Patched

### LINKED ISSUE #62: The Solarized Dark change should be reverted
The changes introduced in #60 should be reverted. The official Solarized Colors (which people expect to install when selecting a theme titled "Solarized Dark") can be found in the [altercation/solarized][1] repo.

I can understand the motives of some people to use a different, more readable color for `Ansi 8 Color`. There has been much talk about this, to the point that some have even [reported it as a bug to altercation/solarized][2]. That's why my recommendation would not be to just revert #60. Instead, we should have a theme called "Solarized Dark" track the same `.itermcolors` as can be found in the [original repo][1], and we should introduce a new theme with a name like "Solarized Dark - Patched ANSI 8". This way people could choose, and not be surprised if they're expecting the defaults.

I'd be more than happy to open a PR for this if you'd support it.

[1]: https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized
[2]: https://github.com/altercation/solarized/issues/220

### PR DESCRIPTION
**Pull request by jez**
I'm open to the name of this theme, but I chose "Solarized Dark - Patched" for
simplicity. I also added a note to the README to clarify the differences between these two schemes.

Fixes #62.

### CODE REVIEW

**Comment by jez** [comment]
And for posterity's sake, here are some screenshots that illustrate the problem: the first is an issue in Vim using the patched theme that isn't present in the non-patched, and the second is a bug with the usage flipped.

screenshot 2016-01-12 00 51 08
screenshot 2016-01-12 00 53 37

**Comment by mbadolato** [comment]
Fantastic, thank you! I'll take a look at it in depth tonight when I get home. Thanks Jake!

**Comment by kevin-smets** [comment]
Hmmm, why provide a patched version and not fix the original one? Just wondering...

**Comment by jez** [comment]
That was precisely my point, and the point made by altercation; neither solution perfectly "fixes" the issue. The "fix" would be to rewrite ANSI escape codes to handle colors in a sane way instead of forcing people into a 16-color palette.

If you look at the screenshots above, you can see that using the patched version makes Vim look bad, and using the non-patched version makes other programs look bad.

Consider reading [this thread] for more information.

[this thread]: https://github.com/altercation/solarized/issues/220#issuecomment-9245966

**Comment by kevin-smets** [comment]
Alright, thanks for the clarification and the info :).

**Pull request merged**
