### PR TITLE
Add Breeze theme

### PR DESCRIPTION
**Pull request by nieltg**
One thing that I missed from my Linux machine was the terminal color scheme. I'm too used to work with KDE terminal and one thing I do to make me able to see the same things on Mac is copying all the color configuration in the Breeze theme in Konsole to iTerm2.

### CODE REVIEW

**Comment by antenore** [comment]
@mbadolato do you need some help to review this and the other PRs? I've some free time available

**Comment by antenore** [comment]
@nieltg amazing job! Thanks! Can you kindly add a screenshot as described in the README.md? Thanks !

**Comment by nieltg** [comment]
@antenore
Hi! Thanks for reviewing my PR. Here is what specified in `README.md` that I followed:
> To include a screenshot, please generate the output using the [screenshotTable.sh script](tools/screenshotTable.sh) in the ```tools``` directory.
> **For screenshot consistency, please have your font set to 13pt Monaco and no transparency on the window**
> It would also be very helpful if you `cd tools/` and run `python3 update_all.py` to generate all formats of your scheme

In this PR, I've attached the screenshot [here](https://github.com/nieltg/iTerm2-Color-Schemes/blob/pull-1/screenshots/breeze.png) at `screenshots/breeze.png`. I also have put its reference at `screenshots/README.md` ([here](https://github.com/mbadolato/iTerm2-Color-Schemes/pull/209/files#diff-69a9e3acaf9e5dcfe8d9e9e51f04392eR77)) and also `README.md` ([here](https://github.com/mbadolato/iTerm2-Color-Schemes/pull/209/files#diff-04c6e90faac2675aa89e2176d2eec7d8R148)).

Please tell me if I'm missing something. Thank you very much.

**Comment by antenore** [comment]
It's perfect, sorry, I didn't see it

**Comment by mbadolato** [comment]
Awesome, thank you!

**Comment by nieltg** [comment]
You're welcome. Thanks for merging my PR. :tada:

**Pull request merged**
