### PR TITLE
fix: GitHub Dark cursortext was white on light gray

### PR DESCRIPTION
**Pull request by ModProg**
## Description

Fix cursortext color in GitHub Dark

### Theme Submission Checklist

- [x] Included theme in iTerm2 format
- [x] Ran `tools/update_all.py` to generate themes in all formats

### CODE REVIEW

**Comment by mbadolato** [comment]
Thank you!

**Comment by jorgeyanesdiez** [comment]
Hey just FYI, this PR merged a bunch of "new" files that were probably meant to overwrite existing ones with different file name case (example: Darkermatrix.yml vs darkermatrix.yml).

**Comment by ModProg** [comment]
> Hey just FYI, this PR merged a bunch of "new" files that were probably meant to overwrite existing ones with different file name case (example: Darkermatrix.yml vs darkermatrix.yml).

maybe this is an error in the script?

**Comment by mbadolato** [comment]
Fixed in #358

**Pull request merged**
