### PR TITLE
Add scheme Purple Rain

### PR DESCRIPTION
**Pull request by msorre2**

### CODE REVIEW

**Comment by msorre2** [comment]
Hey! I'm so sorry I forgot to attach them! I will work on those and send them over ASAP. Thank you so much! 😃

**Comment by mbadolato** [comment]
Awesome, thanks!

**Comment by msorre2** [comment]
Updated the README and included screenshot. Thank you!

**Comment by mbadolato** [comment]
Awesome, thanks! Just one small issue, the screenshot file is named differently than listed in the README (case-sensitivity) 😄

**Comment by mbadolato** [comment]
the png's in the `screenshots` directory should all be lowercase, and words seperated with `-` (though there could be some that buck convention; I haven't looked recently). I'm so as concerned with taht as with the mismatch in name because the readme file won't be able to show it

**Comment by mbadolato** [comment]
Thank you!

**Pull request merged**
