### PR TITLE
Tinacious Design schemes (2) (Dark, Light)

### PR DESCRIPTION
**Pull request by tinacious**
Hello! First I'd like to say thanks for making this repository. I have enjoyed perusing these screenshots and using some of the provided schemes. 

The 2 contributed schemes are based off of my Visual Studio Code colour scheme and contain both light and dark variations: https://marketplace.visualstudio.com/items?itemName=tinaciousdesign.theme-tinaciousdesign

I made an iTerm version and figure I'd share it with the community. My original repository is here: https://github.com/tinacious/iterm-tinacious-design-theme (thanks for the script for generating the output for the screenshots) 🌈 

I've run my screenshots through ImageMagick to resize them down to 650 so that they match the sizing of other screenshots around it in the README. Screenshots included in the PR description are the original, non-resized quality.

I've also run the `update_all.py` script and committed all of the output. Let me know if I missed anything.

Thanks

### CODE REVIEW

**Comment by mbadolato** [comment]
Awesome, thank you!

**Comment by mbadolato** [comment]
Can you add your credit to the bottom of the `README` file too? Thanks!

**Comment by tinacious** [comment]
@mbadolato just added the credit to the bottom of the `README`. Let me know if there's anything else. Thanks!

**Comment by mbadolato** [comment]
Thanks!

**Pull request merged**
