### PR TITLE
Create MaterialDarker and DraculaPlus

### PR DESCRIPTION
**Pull request by jos3s**

### CODE REVIEW

**Comment by mbadolato** [comment]
Hi, thanks for submitting! I would need these in the itermcolors format, which then is used to convert to the other formats

**Comment by jos3s** [comment]
> Hi, thanks for submitting! I would need these in the itermcolors format, which then is used to convert to the other formats

Are there any tools I can use to convert to itermcolors format?

**Comment by mbadolato** [comment]
@jos3s I don't know of any

**Comment by jos3s** [comment]
> @jos3s I don't know of any

I understand, but this way I have no way to go to the expected template

**Comment by mbadolato** [comment]
Added via #251

**Pull request closed without merging**
