### PR TITLE
(+) Add Subliminal theme

### PR DESCRIPTION
**Pull request by gdsrosa**
This commit will add a brand new theme for iTerm2

### CODE REVIEW

**Comment by mbadolato** [comment]
Hi, thanks for submitting! Can you remove all of the changes to the other themes in the `/kitty` directory so that the PR only contains the files affected by the new theme?

Thanks!

**Comment by gdsrosa** [comment]
Done!

**Comment by mbadolato** [comment]
Awesome, thank you! The only other thing is, I don't see the theme and credits added to the Readme file. If you can do that, great, if not, let me know and I can add them for you!

Thank you!!

**Comment by gdsrosa** [comment]
Done! haha

**Comment by mbadolato** [comment]
You rock, thanks much!

**Pull request merged**
