### PR TITLE
Add Raycast color schemes

### PR DESCRIPTION
**Pull request by thomaspaulmann**
Add light/dark color scheme inspired by [Raycast](https://raycast.com).

### CODE REVIEW

**Comment by mbadolato** [comment]
Thanks for submitting! Can you add a credit to the readme too, please?

**Comment by thomaspaulmann** [comment]
Good point. Added the credits.

**Comment by thomaspaulmann** [comment]
BTW I wasn't able to run the `update-all` script locally. Is this a known issue?

**Comment by mbadolato** [comment]
Hmmm, I haven't run the update-all for a while. I can try it and see. 

Thanks for sending this!

**Pull request merged**
