### PR TITLE
Remmina color scheme as per issue #124

### PR DESCRIPTION
**Pull request by antenore**
As agreed I've added the color schemes for Remmina and the Python script.

I'm not Python mother tongue, therefore I've cloned the xrdb2Xresource.py and adapted it for the Remmina color scheme.

I've also updated some missing color schemes

### CODE REVIEW

**Comment by antenore** [comment]
@mbadolato as a side note, the same script can be easily adapted for termite (just 3 lines of code to be changed + the namespace).
If you want I can either add it in this PR or create a new one. 

I'm thinking to add the iTerm2-Color-Schemes as a submodule of Remmina or I'll sync it somehow, do you think it'll be feasible to review the PR and merge it in the next days? 

Sorry for being pushy, I'm quite excited :-P

**Comment by mbadolato** [comment]
Same PR is fine. I should be able to review this week :) Thanks again!

**Comment by antenore** [comment]
Done.

I've added the script for termite, and updated the schemes.

The python script can be surely improved, as I said I'm not (yet) good at it.

Thanks for your support.

**Comment by mbadolato** [comment]
Awesome, thanks! I don't speak python much so wouldn't really be able to tell if it needs to be improved, but if it works, i'm sure it's fine! Did you add a call to the script from the update_all script so that termite stuff gets included when it's run? I didn't see it but there's a lot of files to sort thru

**Comment by antenore** [comment]
Yes, it's there and I tested it.

**Comment by mbadolato** [comment]
Great, thanks!

**Comment by antenore** [comment]
Ouch! I forgot termite in the update script.
I'm really sorry! It's because I didn't push the last commit from my repository. I won't be able to push it till tomorrow.
My bad....

**Comment by mbadolato** [comment]
No worries, just let me know. It may need to go as a separate PR

**Comment by antenore** [comment]
In fact was worse then I thought. I'm opening a new a new PR with the script and the color schemes updated

**Pull request merged**
