### PR TITLE
Adds brand color theme: Social Network book-face

### PR DESCRIPTION
**Pull request by tmjoseantonio**
Hi, 

I would like to contribute to your repo by adding themes with brand colors. For now I'm just uploading a "book-face" color theme but I'm planning on uploading at least five more brand colored themes.

### CODE REVIEW

**Comment by mbadolato** [comment]
I'm always happy to have contributions! My one thought might be to not name them specifically after the brand(s), but rather something similar that conveys meaning. That way we don't have them claiming we're violating brands and copyrighted names by using them in an unofficial capacity. 

Something like Facebook, but not "Facebook" (Book of Faces? Facenet? Something clever 😄 ) etc

Also, could you include screenshot files and update the README with the screen shot and credits?

Thanks!

**Comment by tmjoseantonio** [comment]
That makes a lot of sense, I'll send those updates soon.

**Comment by mbadolato** [comment]
Also, with the FB one, looks like the colors still need to be tweaked. The blue color doesn't show up so I can't see my directories unless I highlight

Without highlighting:

screen shot 2017-10-12 at 2 16 11 pm

With highlighting:

screen shot 2017-10-12 at 2 16 20 pm

**Comment by tmjoseantonio** [comment]
Updated @mbadolato,

Here's an example of the selected text colors
screen shot 2017-10-12 at 16 30 42

**Comment by mbadolato** [comment]
There's still a contrast issue, rendering some of the blue on blue unreadable. In this shot, where the arrow is pointing, there should be directory names showing. They don't show because of the color contrast with the background

screen_shot_2017-12-01_at_11_24_35_am

**Comment by mbadolato** [comment]
Hi @tmjoseantonio ! If you're able to get that tweaked, I'd love to go ahead and merge!

**Comment by tmjoseantonio** [comment]
Right away, sorry I’ve been busy lately.

**Comment by mbadolato** [comment]
Not a problem! Take your time. Just saw the open PR and didn't know if you had seen my last comment a few months back. Cheers!

**Comment by tmjoseantonio** [comment]
Hi @mbadolato I've updated the color contrast so directory names can be visible.

This is what I have:
screen shot 2018-02-25 at 10 32 48 pm

Let me know if this fixes the contrast issue

**Pull request closed without merging**
