### PR TITLE
added ryuuko scheme from @dylanaraps

### PR DESCRIPTION
**Pull request by iandrewt**
adds colour scheme by @dylanaraps from his [dotfiles](https://github.com/dylanaraps/dotfiles)

### CODE REVIEW

**Comment by mbadolato** [comment]
Thanks for submitting this! I've been busy but will merge it in soon 😄

**Comment by iandrewt** [comment]
Just noticed this still hasn't been merged, any updates?

**Comment by mbadolato** [comment]
No sorry. I have a note sitting on my desk to do these. Just haven't gotten to it (need to resize images, update readme, update github pages, generate other scheme formats, etc). Not a ton of work but enough that I haven't got to it :(  Sorry

**Comment by mbadolato** [comment]
(Not just this one, but all submissions currently waiting)

**Comment by iandrewt** [comment]
All good, take your time!

**Comment by mbadolato** [comment]
Thanks!

**Pull request merged**
