### PR TITLE
Add iTerm builtin schemes / Update all

### PR DESCRIPTION
**Pull request by ncornette**
- Add iTerm2 builtin schemes so they can be used in alternative terminals
- Update all

### CODE REVIEW

**Comment by ncornette** [comment]
I could not take the screenshots on my PC, font Monaco doesn't render well on Xterm. Please help me if this is required for this PR

**Comment by mbadolato** [comment]
No problem! I can add the screenshot when I merge in. Thanks!

**Comment by ncornette** [comment]
Added the screenshots, updated readme! All good to me

**Comment by mbadolato** [comment]
Thank you! Sorry, the notification was off on this and it slipped passed me. Oops!

**Comment by mbadolato** [comment]
Or rather, the fact that I needed to go back and do the screenshots slipped past me and I forgot

**Comment by ncornette** [comment]
No worries I could use my branch anyway ;-) Thank you !

**Pull request merged**
