### PR TITLE
Update Dracula theme from upstream

### LINKED ISSUE #487: Dracula colors are wrong
I noticed today, while testing Ghostty, that the theme colors for Dracula are incorrect in comparison with the official color scheme.

`Bold Color` and `Foreground Color` appear to be different compared to the colors specified by the official Dracula iterm theme - https://raw.githubusercontent.com/dracula/iterm/refs/heads/master/Dracula.itermcolors

Can these themes be adjusted to respect the official color scheme?

### PR DESCRIPTION
**Pull request by akx**
## Description

Fixes #487.

### Theme ~Submission~ Update Checklist

- [x] Included theme in iTerm2 format
- [x] Included 600x300 screenshot, 13pt Monaco font, no transparency
- [x] Updated `README.md` with new theme and screenshot
- [x] Updated `CREDITS.md` with new theme
- [x] Ran `tools/gen.py` to generate themes in all formats
- [x] Updated `screenshots/README.md` with new theme

### CODE REVIEW

**Comment by mbadolato** [comment]
Great, thank you!

**Comment by Gelmo** [comment]
@mbadolato @akx There must have been another inconsistency. All of the updated themes that use hex instead of ansi were adjusted to use the wrong color.  For example, Ghostty has:
```
background = #1e1f29
foreground = #e6e6e6
```
However, the correct values are:
```
background = #282a36
foreground = #f8f8f2
```
Based on Dracula's official documentation - https://draculatheme.com/contribute

In other words, foreground was correct but was changed anyway, and background was incorrect and has not been fixed.

**Comment by Gelmo** [comment]
If these were all generated from the iterm2 theme, it seems possible that that official dracula theme for iterm2 does not respect dracula colors...

**Comment by akx** [comment]
@Gelmo This is what the Dracula I used here looks like in iTerm2.
Screenshot 2025-01-03 at 8 22 34

**Comment by Gelmo** [comment]
@akx The background color in that screenshot is incorrect. That uses #24252F, while the official Dracula theme color palette specifies #282A36

https://draculatheme.com/contribute

**Comment by Gelmo** [comment]
I've just taken a look, and the colors at https://github.com/dracula/iterm do not respect Dracula's real colors lol

**Comment by akx** [comment]
> I've just taken a look, and the colors at https://github.com/dracula/iterm do not respect Dracula's real colors lol

The issue is that those colors don't have a specified colorspace (#349, #354), so they're interpreted as device colors by your iTerm, and when you take a screenshot, that'll be in yet another colorspace.

IOW, it's a bit fiddly to get the same [sRGB](https://en.wikipedia.org/wiki/SRGB) hexes as specified in color documentation (such as Dracula's) if they've already been transformed to iTerm schemes.

If @mbadolato doesn't oppose it, I'd love to write a PR to make it possible to source schemes from hex colors (and thus convert those themes _to_ well-color-schemed iTerm schemes), and then define Darcula in terms of the official color definition.

**Comment by akx** [comment]
@Gelmo Do these look more correct?

Screenshot 2025-01-07 at 15 19 59

**Comment by Gelmo** [comment]
> The issue is that those colors don't have a specified colorspace (#349, #354), so they're interpreted as device colors by your iTerm, and when you take a screenshot, that'll be in yet another colorspace.
> 
> IOW, it's a bit fiddly to get the same [sRGB](https://en.wikipedia.org/wiki/SRGB) hexes as specified in color documentation (such as Dracula's) if they've already been transformed to iTerm schemes.

That is very interesting; great catch!

> If @mbadolato doesn't oppose it, I'd love to write a PR to make it possible to source schemes from hex colors (and thus convert those themes _to_ well-color-spaced iTerm schemes), and then define Darcula in terms of the official color definition.

Great idea.
- YAML file for each theme
- Generate all schemes from defined colors, even if the upstream theme only provides official schemes and no documentation
- (Mandatory) Define the color encoding used for the values that follow
- (Mandatory) Define the values in the format officially provided by theme docs, if it exists, or from the upstream scheme if not.
  - Contributor guidelines will need to be updated to inform submitters of new themes about the need to refer to upstream documentation rather than upstream schemes, if such documentation exists. (For example, in the case of Dracula, since the official documentation exists, do not use the official Dracula scheme)
- (Optional) Define a list of official upstream scheme files that should be used as-is instead of generating and overwriting
  - This way, if an upstream scheme has a difference from its official theme documentation, and there's a real reason for that to be used instead of what would be generated by the script, that can remain unchanged while allowing schemes for other applications to still be generated from the defined values.

> @Gelmo Do these look more correct?

I'll post a response to this in your new PR

**Comment by mbadolato** [comment]
@akx I'd be all for it! Anything that makes things simpler, and more correct!

To clarify, are you talking about changing things so a definition file is used for themes, then all (including iterm's) are built from those? It would make life simpler, and allow non iTerm users to submit themes that way.

**Comment by akx** [comment]
@mbadolato Great! 😁 #512 (still a draft, see within) implements this in a non-intrusive way: both iTerm schemes and YAML-based schemes are source material, and where defined, a YAML-based scheme is considered the source material from which an iTerm scheme is generated. :)

**Pull request merged**
