### PR TITLE
iTerm to Terminal converter

### LINKED ISSUE #305: iterm2terminal.swift script issue
```
./iterm2terminal.swift:106:45: warning: 'archivedData(withRootObject:)' was deprecated in macOS 10.14: Use +archivedDataWithRootObject:requiringSecureCoding:error: instead
            let colorData = NSKeyedArchiver.archivedData(withRootObject: color)
                                            ^
./iterm2terminal.swift:118:28: warning: 'archivedData(withRootObject:)' was deprecated in macOS 10.14: Use +archivedDataWithRootObject:requiringSecureCoding:error: instead
    return NSKeyedArchiver.archivedData(withRootObject: font)
                           ^
unable to load ./iterm2terminal.swift
converting ../schemes/HaX0R_R3D.itermcolors -> ../schemes/HaX0R_R3D.terminal
```

When trying to use the `iterm2terminal.swift` script in macOS BigSur, the aforementioned error message is popping up.

### PR DESCRIPTION
**Pull request by jdhmtl**
Created a Python converter for iTerm2 to Terminal.app formats.
Closes #305

### CODE REVIEW

**Comment by jdhmtl** [comment]
**NOTE:** In creating this, I noticed something of a lack of consistency across existing Terminal themes. Colors are specified as decimals, but the number of decimal places is inconsistent across files, and sometimes within the same file. What this means in practical terms is that, while the RGB hex values will come out the same, there will be differences in the generated `.terminal` files. For this reason, I have _not_ included a call to `iterm2terminal.py` in the `udpate_all.py` script. It would have resulted in a sizeable, and mostly illegible, diff. If you decide to go ahead with this, I will need to generate a diff of the `schemes` and `terminal` directories to find which Terminal themes are missing and run the converter against only those.

**Comment by mbadolato** [comment]
Is this good to go, aside from the regenerating?

**Comment by jdhmtl** [comment]
Should be, yes. Given the scenario I described above, I haven't come up with a reasonable automated test for this. I have spot-checked a number of themes, comparing the RGB values of those produced by the converter to those already in the repo in Terminal.app format, and they have all matched. Also, as this is excluded from `update_all.py`, at least for now, errors can be spotted and reported without any significant impacts on the repository.

**Comment by mbadolato** [comment]
Sounds good, thanks!

**Pull request merged**
