### PR TITLE
Color palette tweaks for DarkMatrix and a new eye-friendly DarkerMatrix for low light environment

### PR DESCRIPTION
**Pull request by i3d**
1. Make Dark Matrix less intimidating in color contrast. 2. Introduce an eye-friendly Darker Matrix theme with even less color contrast for dark/low light environment. Color palettes are still following the same style with only minor changes to suit the low contrast schema.

### CODE REVIEW

**Comment by mbadolato** [comment]
Does this require new screenshots?

**Comment by i3d** [comment]
For the darker matrix theme, as I mentioned that the patterns are pretty much the same, just darker. Do you think it should also have its own screenshot?

**Comment by mbadolato** [comment]
If the colors are different than the current screenshot, then yes it should be included. thanks!

**Comment by i3d** [comment]
Ok, I have updated the screenshots. I've also updated the README to reflect the new changes.

**Comment by mbadolato** [comment]
Thanks!

**Pull request merged**
