### PR TITLE
Press b to go back in preview history

### PR DESCRIPTION
**Pull request by jeffppfa**
I added a feature to see the previous color scheme when using the preview script. I am new to ruby so my changes might not be idiomatic. I used two stacks to implement this feature.

### CODE REVIEW

**Comment by jeffppfa** [comment]
@junegunn - I see that you originally wrote this script. Can you step in and review?

**Comment by junegunn** [comment]
Hi, I would do it this way:

```patch
diff --git a/tools/preview.rb b/tools/preview.rb
index 963b4be..e152368 100755
--- a/tools/preview.rb
+++ b/tools/preview.rb
@@ -21,6 +21,7 @@ if ENV.has_key? 'TMUX'
 end
 
 preview = files.length > 1
+history = []
 until files.empty?
   file = files.shift
   print "[#{File.basename file, '.*'}] " if preview
@@ -59,7 +60,15 @@ until files.empty?
         'cursor text'   => 'm',
       }.fetch(type, '%x' % type.to_i) << rgb << "\e\\"
     end
-    break if files.empty? || [3.chr, "\e"].include?(IO.console.getch)
+
+    case IO.console.getch.ord
+    when 127   # backspace
+      files.unshift *[history.pop, file].compact
+    when 3, 27 # ctrl-c, esc
+      break
+    else
+      history << file
+    end
   rescue Exception
     print '(X) '
   end
```

(Note that I'm expecting backspace (127) instead of "b" (`'b'.ord`) here.)

**Comment by mbadolato** [comment]
@jeffppfa Any thoughts on the suggestion provided in the diff above?

**Comment by jeffppfa** [comment]
@mbadolato sorry, I forgot about this request and the fork was deleted. I moved this request (with junegunn's suggestions) to https://github.com/mbadolato/iTerm2-Color-Schemes/pull/113

**Pull request closed without merging**
