### PR TITLE
Fix oxocarbon color theme colors

### PR DESCRIPTION
**Pull request by hqnna**
## Description

In the pull request where I added the Oxocarbon theme, the colors were broken for some reason in the generated files, they should be fixed in this pull request. I have loaded them in my terminal to ensure they match the screenshot.

### Theme Submission Checklist

- [x] Included theme in iTerm2 format
- [x] Included 600x300 screenshot, 13pt Monaco font, no transparency
- [x] Updated `README.md` with new theme and screenshot
- [x] Updated `CREDITS.md` with new theme
- [x] Ran `tools/gen.py` to generate themes in all formats
- [x] Updated `screenshots/README.md` with new theme

### CODE REVIEW

**Comment by hqnna** [comment]
dont merge this just yet

**Comment by hqnna** [comment]
ok we good.

**Comment by mbadolato** [comment]
Thank you!

**Comment by mbadolato** [comment]
Does it need an updated screenshot?

**Comment by hqnna** [comment]
> Does it need an updated screenshot?

No the screenshot is fine, i just exported the wrong theme from iterm2 originally.

**Pull request merged**
