### PR TITLE
add Retro Neon theme

### PR DESCRIPTION
**Pull request by Akevic**

### CODE REVIEW

**Comment by mbadolato** [comment]
Thanks for submitting! Can you add the screenshot and credit to the README file please?

**Comment by Akevic** [comment]
Sure, I added credit and screenshot.

**Comment by mbadolato** [comment]
I see the credit in the README but not the screenshot

**Comment by Akevic** [comment]
Hm in files changed I see that it added an image but I can't actually see image.
I probably messed something up, I'll look into it.

**Comment by mbadolato** [comment]
@Akevic were you able to add that?

**Pull request closed without merging**
