### PR TITLE
Add rio terminal template

### PR DESCRIPTION
**Pull request by tranzystorek-io**
## Description

Adds a template for the rio terminal: https://raphamorim.io/rio/

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
Note: this shouldn't be merged until new changes in rio themes have been released: https://github.com/raphamorim/rio/issues/125

**Comment by mbadolato** [comment]
Cool, thanks! Let me know when it's good to go!

**Comment by tranzystorek-io** [comment]
rio 0.0.9 is up, this PR is ready to merge 😊

**Comment by tranzystorek-io** [comment]
@mbadolato pinging for the merge 😁

**Comment by mbadolato** [comment]
Thank you!

**Pull request merged**
